name: publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest


    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4

      - name: Install packages
        run: |
          npm ci

      - name: Download VSIX artifact
        uses: actions/download-artifact@v4
        with:
          name: vsix

      - name: Publish VSIX
        env:
          VSCE_PAT: ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
        run: |
          npm run publish
